apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gamelibrarymanager
  annotations:
    kompose.cmd: D:\Applications\Scoop\apps\kompose\current\kompose.exe convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 4
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      annotations:
        kompose.cmd: D:\Applications\Scoop\apps\kompose\current\kompose.exe convert
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: game-lib-secrets
                  key: db-pass
            - name: DB_URL
              value: jdbc:postgresql://db:5433/gamelib
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: game-lib-secrets
                  key: db-user
          image: matheusjtavares/gamelibrarymanager-api
          name: game-lib-api
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      restartPolicy: Always
