apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: gamelibrarymanager
  labels:
    io.kompose.service: db
  name: db
spec:
  serviceName: "db"
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  template:
    metadata:
      labels:
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: game-lib-secrets
                  key: db-name
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: game-lib-secrets
                  key: db-pass
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: game-lib-secrets
                  key: db-user
          image: postgres:16-alpine
          name: game-lib-db
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Mi
